/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "x2y.h"

float rate = 2.0;

float *
updaterate_3_svc(float *argp, struct svc_req *rqstp)
{
	static float  result;

	result = *argp;

	return &result;
}

float *
convert_x2y_3_svc(float *argp, struct svc_req *rqstp)
{
	static float  result;

	result = *argp * rate;

	return &result;
}
