/*
 * Automatically generated by jrpcgen 1.0.7 on 09/10/14 11:56
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "x2y" ONC/RPC program.
 */
public interface x2y {
    public static final int finance = 0x20002000;
    public static final int convert_x2y_3 = 2;
    public static final int VERS = 3;
    public static final int updateRate_3 = 1;
}
// End of x2y.java
