/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _X2Y_H_RPCGEN
#define _X2Y_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define finance 0x20002000
#define VERS 3

#if defined(__STDC__) || defined(__cplusplus)
#define updateRate 1
extern  float * updaterate_3(float *, CLIENT *);
extern  float * updaterate_3_svc(float *, struct svc_req *);
#define convert_x2y 2
extern  float * convert_x2y_3(float *, CLIENT *);
extern  float * convert_x2y_3_svc(float *, struct svc_req *);
extern int finance_3_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define updateRate 1
extern  float * updaterate_3();
extern  float * updaterate_3_svc();
#define convert_x2y 2
extern  float * convert_x2y_3();
extern  float * convert_x2y_3_svc();
extern int finance_3_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_X2Y_H_RPCGEN */
