/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "x2y.h"


void
finance_3(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	float  updaterate_3_arg;
	float  *result_2;
	float  convert_x2y_3_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, finance, VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = updaterate_3(&updaterate_3_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = convert_x2y_3(&convert_x2y_3_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	finance_3 (host);
exit (0);
}
